version: '3.8'
services:
  # 1. Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  # 2. Kafka
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "weather-readings:1:1,heavy-rain-alerts:1:1"
    depends_on:
      - zookeeper

  # 3. Postgres Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql

  # 4. Central Station
  central-station:
    build:
      context: .
      dockerfile: Dockerfile.central
    environment:
      KAFKA_SERVER: kafka:9092
      DB_URL: jdbc:postgresql://postgres:5432/weatherdb
      DB_USER: postgres
      DB_PASS: password
    depends_on:
      - kafka
      - postgres

  # 5. Weather Station (Running 1 instance for test)
  weather-station:
    build:
      context: .
      dockerfile: Dockerfile.weather
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka